name: hello-world-action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: robearlam/SharedGitHubAction/cloud-login@main
        with:
          command: 'cloud --help'