name: hello-world-action

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: robearlam/SharedGitHubAction/init@main

      # - uses: robearlam/SharedGitHubAction/action2@main